
export const SET_HEAD_BACKGROUND = 'SET_HEAD_BACKGROUND';
export const SET_FOOTER = 'SET_FOOTER';
export const SET_PAGES = 'SET_PAGES';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_COMPONENTS_PAGE = 'SET_COMPONENTS_PAGE';
